apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eleduck-analytics

resources:
  - namespace.yaml
  # 1Password items
  - 1password/onepassworditem-postgres.yaml
  - 1password/onepassworditem-airbyte-youtube.yaml
  - 1password/onepassworditem-airbyte-twitch.yaml
  - 1password/onepassworditem-airbyte-twitter.yaml
  - 1password/onepassworditem-airbyte-linkedin.yaml
  - 1password/onepassworditem-airbyte-github.yaml
  - 1password/onepassworditem-airbyte-stripe.yaml
  - 1password/onepassworditem-airbyte-notion.yaml
  - 1password/onepassworditem-metabase.yaml
  # Infrastructure
  - postgres/
  - airbyte/
  - metabase/
  - sqlmesh/
