apiVersion: v1
kind: ServiceAccount
metadata:
  name: airbyte
  namespace: eleduck-analytics
  labels:
    app: airbyte
    app.kubernetes.io/name: airbyte
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airbyte
  namespace: eleduck-analytics
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airbyte
  namespace: eleduck-analytics
subjects:
  - kind: ServiceAccount
    name: airbyte
    namespace: eleduck-analytics
roleRef:
  kind: Role
  name: airbyte
  apiGroup: rbac.authorization.k8s.io
